# Generated by Django 5.0.6 on 2024-06-19 09:10

import django.db.models.deletion
import posty.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('text_template', models.TextField()),
                ('html_template', models.TextField()),
                ('preview_data', models.JSONField(blank=True, null=True)),
            ],
            bases=(posty.models.EmailPreviewMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.CharField(max_length=255)),
                ('to_email', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('text_content', models.TextField()),
                ('html_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='posty.emailtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(posty.models.EmailPreviewMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('deferred', 'Deferred'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('unknown', 'Unknown')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posty.email')),
            ],
        ),
    ]
